# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDko59YaiRr5bKKweZtxtiL9-mqGuni4
"""

!pip install face_recognition

from google.colab import drive
import os
import face_recognition
import pickle
import numpy as np

drive.mount('/content/drive')

dataset_path = '/content/drive/MyDrive/60 tấm selfies - sáng T2'

known_encodings = []
known_names = []

print("[INFO] Bắt đầu quét và xử lý hình ảnh...")


for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(('.jpg', '.jpeg', '.png')):
            image_path = os.path.join(root, file)

            folder_name = os.path.basename(root)
            if folder_name != '60 tấm selfies':
                name = folder_name
            else:
                name = os.path.splitext(file)[0].split('_')[0]

            try:
                image = face_recognition.load_image_file(image_path)

                encodings = face_recognition.face_encodings(image)

                if len(encodings) > 0:
                    known_encodings.append(encodings[0])
                    known_names.append(name)
                    print(f"[THÀNH CÔNG] Đã học khuôn mặt của: {name} (File: {file})")
                else:
                    print(f"[CẢNH BÁO] Không tìm thấy khuôn mặt trong ảnh: {file}")
            except Exception as e:
                print(f"[LỖI] Không thể xử lý file {file}. Chi tiết: {e}")


model_output_path = "/content/drive/MyDrive/face_recognition_model.pickle"

data = {"encodings": known_encodings, "names": known_names}
with open(model_output_path, "wb") as f:
    f.write(pickle.dumps(data))

print("\n=======================================================")
print(f"[HOÀN THÀNH] Quá trình huấn luyện kết thúc thành công!")
print(f"[INFO] Tổng số khuôn mặt đã lưu: {len(known_encodings)}")
print(f"[INFO] File model đã được lưu tại: {model_output_path}")
print("=======================================================")

import face_recognition
import pickle
import numpy as np
import cv2
from google.colab.patches import cv2_imshow
from PIL import Image, ImageFont, ImageDraw

def predict_face(test_image_path):
    model_path = "/content/drive/MyDrive/face_recognition_model.pickle"
    with open(model_path, "rb") as f:
        data = pickle.loads(f.read())

    image = face_recognition.load_image_file(test_image_path)
    output_image = cv2.imread(test_image_path)

    output_image_rgb = cv2.cvtColor(output_image, cv2.COLOR_BGR2RGB)
    pil_image = Image.fromarray(output_image_rgb)
    draw = ImageDraw.Draw(pil_image)

    try:
        font_path = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
        font = ImageFont.truetype(font_path, 32)
    except:
        font = ImageFont.load_default()

    face_locations = face_recognition.face_locations(image)
    face_encodings = face_recognition.face_encodings(image, face_locations)

    for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):
        matches = face_recognition.compare_faces(data["encodings"], face_encoding, tolerance=0.45)
        name = "Unknown"

        face_distances = face_recognition.face_distance(data["encodings"], face_encoding)
        if len(face_distances) > 0:
            best_match_index = np.argmin(face_distances)
            if matches[best_match_index]:
                name = data["names"][best_match_index]

        draw.rectangle(((left, top), (right, bottom)), outline=(0, 255, 0), width=3)
        draw.text((left, max(0, top - 35)), name, font=font, fill=(0, 255, 0))

        print(f"Phát hiện khuôn mặt: {name}")

    output_image_final = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)

    cv2_imshow(output_image_final)

duong_dan_anh_test = "/content/drive/MyDrive/60 tấm selfies - sáng T2/Đinh Hữu Khánh Anh/1000017983.jpg"
predict_face(duong_dan_anh_test)